config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'characters#home'

  resources :characters

  namespace :api do
    namespace :v1 do
      resources :equipments
    end
  end

  namespace :api do
    namespace :v1 do
      resources :spells
    end
  end

  namespace :api do
    namespace :v1 do
      resources :characters
    end
  end
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true
  validates :profession, presence: true
  validates :hit_dice, presence: true

  belongs_to :user
  self.table_name = "characters"
end

app/controllers/api/v1/characters_controller.rb
class Api::V1::CharactersController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    body=request.body.read
    parsed=JSON.parse(body)
    character=Character.new(parsed)
    character.user_id = current_user.id
    character.name = current_user.name
    if character.save
      render json: { message: ["It worked!"]}
    else
      render json: { message: character.errors.full_messages}
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def home
    @current_user=current_user
  end

  def index
    @characters = current_user.characters
  end

  def show
    @character=Character.find(params[:id])
  end

  def create
  end

  def edit
    @character=Character.find(params[:id])
    @creation_stats=[nil,15,14,13,12,10,8]
  end

  def update
    @character=Character.find(params[:id])
    @character.update(character_params)

    if character_params['strength'].to_i == 15 || character_params['strength'].to_i == 14
      @character.strength_mod = 2
    elsif character_params['strength'].to_i == 13 || character_params['strength'].to_i == 12
      @character.strength_mod = 1
    elsif character_params['strength'].to_i == 10
      @character.strength_mod = 0
    elsif character_params['strength'].to_i == 8
      @character.strength_mod = (-1)
    end

    if character_params['dexterity'].to_i == 15 || character_params['dexterity'].to_i == 14
      @character.dexterity_mod = 2
    elsif character_params['dexterity'].to_i == 13 || character_params['dexterity'].to_i == 12
      @character.dexterity_mod = 1
    elsif character_params['dexterity'].to_i == 10
      @character.dexterity_mod = 0
    elsif character_params['dexterity'].to_i == 8
      @character.dexterity_mod = (-1)
    end

    if character_params['constitution'].to_i == 15 || character_params['constitution'].to_i == 14
      @character.constitution_mod = 2
    elsif character_params['constitution'].to_i == 13 || character_params['constitution'].to_i == 12
      @character.constitution_mod = 1
    elsif character_params['constitution'].to_i == 10
      @character.constitution_mod = 0
    elsif character_params['constitution'].to_i == 8
      @character.constitution_mod = (-1)
    end

    if character_params['intelligence'].to_i == 15 || character_params['intelligence'].to_i == 14
      @character.intelligence_mod = 2
    elsif character_params['intelligence'].to_i == 13 || character_params['intelligence'].to_i == 12
      @character.intelligence_mod = 1
    elsif character_params['intelligence'].to_i == 10
      @character.intelligence_mod = 0
    elsif character_params['intelligence'].to_i == 8
      @character.intelligence_mod = (-1)
    end

    if character_params['wisdom'].to_i == 15 || character_params['wisdom'].to_i == 14
      @character.wisdom_mod = 2
    elsif character_params['wisdom'].to_i == 13 || character_params['wisdom'].to_i == 12
      @character.wisdom_mod = 1
    elsif character_params['wisdom'].to_i == 10
      @character.wisdom_mod = 0
    elsif character_params['wisdom'].to_i == 8
      @character.wisdom_mod = (-1)
    end

    if character_params['charisma'].to_i == 15 || character_params['charisma'].to_i == 14
      @character.charisma_mod = 2
    elsif character_params['charisma'].to_i == 13 || character_params['charisma'].to_i == 12
      @character.charisma_mod = 1
    elsif character_params['charisma'].to_i == 10
      @character.charisma_mod = 0
    elsif character_params['charisma'].to_i == 8
      @character.charisma_mod = (-1)
    end

    @character.maximum_hp = 10 + @character.constitution_mod
    @character.current_hp = @character.maximum_hp

    redirect_to character_path(@character)
  end

  def destroy
    @character=Character.find(params[:id])
    @character.destroy
    redirect_to characters_path
  end

  private

  def character_params
    params.require(:character).permit(:strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :race, :alignment)
  end
end

app/views/characters/edit.html.erb
<%= form_for(@character) do |f| %>
  <div class="form1">
    <div>
      <%= f.label :race %>
      <%= f.text_field :race %>
    </div>

    <div>
      <%= f.label :alignment %>
      <%= f.text_field :alignment %>
    </div>

    <div class="field1">
      <%= f.label :strength %>
      <%= f.select :strength, @creation_stats %>
    </div>
    <div class="field1">
      <%= f.label :dexterity %>
      <%= f.select :dexterity, @creation_stats %>
    </div>
    <div class="field1">
      <%= f.label :constitution %>
      <%= f.select :constitution, @creation_stats %>
    </div>
    <div class="field1">
      <%= f.label :intelligence %>
      <%= f.select :intelligence, @creation_stats %>
    </div>
    <div class="field1">
      <%= f.label :wisdom %>
      <%= f.select :wisdom, @creation_stats %>
    </div>
    <div class="field1">
      <%= f.label :charisma %>
      <%= f.select :charisma, @creation_stats %>
    </div>

    <div class="actions">
      <%= f.submit value="Submit Stats" %>
    </div>
  </div>
<% end %>

app/views/characters/home.html.erb
<div class='wrapper'>
  <div id='app'></div>

  <div id='login'>
    <% unless current_user %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    <% else %>
      <img src='<%= @current_user.image %>' />
      <%= link_to 'My Characters', characters_path %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% end %>
  </div>
</div>

app/views/characters/index.html.erb
<ul>
  <% @characters.each do |c| %>
    <li>
      <%= link_to c.profession, character_path(c) %>
    </li>
  <% end %>
</ul>
<%= link_to 'Home', root_path %>

app/views/characters/show.html.erb
Level <%= @character.level %> <%= @character.profession %>

<%= link_to 'Home', root_path %>

<% if @character.level == 0 && @character.strength.nil? %>
<!-- CHARACTER CREATION -->
<%= link_to "Distribute Stats", edit_character_path(@character) %>


<% else %>
<!-- CHARACTER PAGE -->
<div>
  strength: <%= @character.strength %>
</div>
<div>
  strength mod: <%= @character.strength_mod %>
</div>
<div>
  dexterity: <%= @character.dexterity %>
</div>
<div>
  dexterity mod: <%= @character.dexterity_mod %>
</div>
<div>
  constitution: <%= @character.constitution %>
</div>
<div>
  constitution mod: <%= @character.constitution_mod %>
</div>
<div>
  intelligence: <%= @character.intelligence %>
</div>
<div>
  intelligence mod: <%= @character.intelligence_mod %>
</div>
<div>
  wisdom: <%= @character.wisdom %>
</div>
<div>
  wisdom mod: <%= @character.wisdom_mod %>
</div>
<div>
  charisma: <%= @character.charisma %>
</div>
<div>
  charisma mod: <%= @character.charisma_mod %>
</div>

<%= link_to "Delete Character", @character, method: :delete, data: { confirm: 'Are you sure?' }%>
<% end %>